import os
import csstyle

from local import LOCAL
from sitenco import SITE_ROOT, PROJECTS_PATH

def css():
    local_filename = os.path.join('static', 'css', 'style.css')
    filenames = (
        os.path.join(SITE_ROOT, local_filename),
        os.path.join(PROJECTS_PATH, LOCAL.project_name, local_filename))

    text = "/* Generated by CSStyle */\n\n"

    for filename in filenames:
        text += open(filename).read()

    for engine in csstyle.BROWSERS:
        browser_parser = getattr(csstyle, engine)
        parser = csstyle.Parser(filenames)
        text += "\n\n/* CSS for %s */\n\n" % engine
        text += repr(browser_parser.transform(parser, keep_existant=False))

    return text
